# ── Release metadata (edit before every build) ─────────────────────────────

__version__      = "1.0.1"      
__version_tuple__ = (1, 0, 1, 0)

__author__       = "Max0Black"
__company__      = "Max0Black"
__product_name__ = "Useful Utilities Collection"
__description__  = "Useful Utilities Collection – System Tools"
__copyright__    = f"© 2026 {__author__}"
__exe_name__     = "UUC.exe"
__internal_name__ = "UUC"

# ── Windows locale for version info (English US + Unicode) ─────────────────
_LOCALE_ID       = "040904B0"
_TRANSLATION     = (0x0409, 1200)

# ── Helper: generate version_info.txt content ───────────────────────────────

def generate_version_info_txt() -> str:
    fv = ",".join(str(x) for x in __version_tuple__)
    fv_str = ".".join(str(x) for x in __version_tuple__)

    return f"""\
# UTF-8
#
# Auto-generated by src/useful_utilities_collection/version.py – do NOT edit manually.
# Edit version.py and run `python build.py` to regenerate.
#
# Embedded Windows version metadata.  Keeping CompanyName / ProductName
# consistent across releases lets SmartScreen recognise the binary as an
# update of the same trusted program, rather than treating it as a new unknown
# executable each time.

VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({", ".join(str(x) for x in __version_tuple__)}),
    prodvers=({", ".join(str(x) for x in __version_tuple__)}),
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo(
      [
        StringTable(
          u'{_LOCALE_ID}',
          [
            StringStruct(u'CompanyName', u'{__company__}'),
            StringStruct(u'FileDescription', u'{__description__}'),
            StringStruct(u'FileVersion', u'{fv_str}'),
            StringStruct(u'InternalName', u'{__internal_name__}'),
            StringStruct(u'LegalCopyright', u'{__copyright__}'),
            StringStruct(u'OriginalFilename', u'{__exe_name__}'),
            StringStruct(u'ProductName', u'{__product_name__}'),
            StringStruct(u'ProductVersion', u'{fv_str}'),
          ]
        )
      ]
    ),
    VarFileInfo([VarStruct(u'Translation', [{hex(_TRANSLATION[0])}, {_TRANSLATION[1]}])])
  ]
)
"""


if __name__ == "__main__":
    # Quick sanity-check: print the generated file
    print(generate_version_info_txt())
